version: '3.7'

services:
  farapp:
    build:
      dockerfile: Dockerfile
      context: ./
    ports:
      - 8080:8080
    restart: 'always'
    networks:
      - 'far_app'
    volumes:
      - type: bind
        source: './data/'
        target: '/data/'
networks:
  far_app:
    name: 'far_app'
volumes:
  data:
    driver: local
